# Generated by Django 5.2 on 2025-04-11 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_cat_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='image',
            field=models.CharField(choices=[('cat-in-box.svg', 'Cat in Box'), ('cool-cat.svg', 'Cool Cat'), ('happy-cat.svg', 'Happy Cat'), ('nerd-cat.svg', 'Nerd Cat'), ('sk8r-boi-cat.svg', 'Skater Cat'), ('teacup-cat.svg', 'Teacup Cat')], default='cat-in-box.svg', max_length=100),
        ),
    ]
